
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1compiladores1.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Sim_Coma = 18;
  public static final int P_R_Etiquetas = 7;
  public static final int P_R_Titulo = 4;
  public static final int Par_Izq = 25;
  public static final int P_R_Unir = 9;
  public static final int Sim_Comillas = 16;
  public static final int Par_Der = 26;
  public static final int Entero = 32;
  public static final int P_R_Valores = 8;
  public static final int T_G_Porcentajes = 14;
  public static final int Oper_Div = 24;
  public static final int P_R_Def = 2;
  public static final int P_R_Total = 11;
  public static final int Cadena = 31;
  public static final int Oper_Resta = 22;
  public static final int EOF = 0;
  public static final int P_R_Extra = 12;
  public static final int Oper_Suma = 21;
  public static final int Sim_Punto = 17;
  public static final int P_R_Ejecutar = 15;
  public static final int Decimal = 33;
  public static final int Corch_Izq = 29;
  public static final int Llave_Izq = 27;
  public static final int Sim_PComa = 20;
  public static final int error = 1;
  public static final int T_G_Cantidad = 13;
  public static final int P_R_Tipo = 10;
  public static final int P_R_TipoGrafico = 3;
  public static final int Corch_Der = 30;
  public static final int Llave_Der = 28;
  public static final int P_R_EjeY = 6;
  public static final int P_R_EjeX = 5;
  public static final int Oper_Multi = 23;
  public static final int Sim_DPuntos = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "P_R_Def",
  "P_R_TipoGrafico",
  "P_R_Titulo",
  "P_R_EjeX",
  "P_R_EjeY",
  "P_R_Etiquetas",
  "P_R_Valores",
  "P_R_Unir",
  "P_R_Tipo",
  "P_R_Total",
  "P_R_Extra",
  "T_G_Cantidad",
  "T_G_Porcentajes",
  "P_R_Ejecutar",
  "Sim_Comillas",
  "Sim_Punto",
  "Sim_Coma",
  "Sim_DPuntos",
  "Sim_PComa",
  "Oper_Suma",
  "Oper_Resta",
  "Oper_Multi",
  "Oper_Div",
  "Par_Izq",
  "Par_Der",
  "Llave_Izq",
  "Llave_Der",
  "Corch_Izq",
  "Corch_Der",
  "Cadena",
  "Entero",
  "Decimal"
  };

  /* non terminals */
  static final int NT$3 = 24;
  static final int NT$2 = 23;
  static final int NT$1 = 22;
  static final int TUPLASD = 14;
  static final int NT$0 = 21;
  static final int TUPLAS = 13;
  static final int EJECUCION = 18;
  static final int TUPLA = 15;
  static final int NUMEROS = 10;
  static final int TUPLAD = 16;
  static final int LISTA_TUPLAS = 12;
  static final int RECUPERACION_VALOR_ATRIBUTO = 4;
  static final int DEFINICIONES = 1;
  static final int CADENAS = 7;
  static final int CADENASD = 8;
  static final int NT$15 = 36;
  static final int NT$14 = 35;
  static final int EJECUCIONDD = 20;
  static final int NT$13 = 34;
  static final int NT$12 = 33;
  static final int NT$11 = 32;
  static final int NT$10 = 31;
  static final int LISTA_NUMEROS = 9;
  static final int ATRIBUTOS = 3;
  static final int EJECUCIOND = 19;
  static final int DECLARACION_ATRIBUTO = 5;
  static final int LISTA_CADENAS = 6;
  static final int EXPRESION_MATEMATICA = 17;
  static final int NUMEROSD = 11;
  static final int INICIO = 0;
  static final int DEFINICION = 2;
  static final int NT$9 = 30;
  static final int NT$8 = 29;
  static final int NT$7 = 28;
  static final int NT$6 = 27;
  static final int NT$5 = 26;
  static final int NT$4 = 25;
}

